spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymdb
    username: myuser
    password: secret
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs