package com.gymtracker.gym.aiPlans.client;

import com.gymtracker.gym.aiPlans.dto.GeneratePlanRequest;
import com.gymtracker.gym.aiPlans.generated.GeneratedDay;
import com.gymtracker.gym.aiPlans.generated.GeneratedExercise;
import com.gymtracker.gym.aiPlans.generated.GeneratedProgram;
import com.gymtracker.gym.aiPlans.generated.GeneratedWeek;
import com.gymtracker.gym.aiPlans.history.TrainingHistorySummary;
import com.gymtracker.gym.trainingPrograms.model.ProgramGoal;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Deterministic stand-in for the real Claude client — used whenever gymtracker.ai.enabled
 * is false (the default), so local dev and tests never need an API key or make a real call.
 */
@Component
@ConditionalOnProperty(name = "gymtracker.ai.enabled", havingValue = "false", matchIfMissing = true)
public class StubWorkoutPlanAiClient implements WorkoutPlanAiClient {

    private static final int EXERCISES_PER_DAY = 4;

    @Override
    public AiGenerationResult generate(GeneratePlanRequest request, TrainingHistorySummary history) {
        List<GeneratedWeek> weeks = new ArrayList<>();
        for (int weekNumber = 1; weekNumber <= request.durationWeeks(); weekNumber++) {
            boolean deload = request.durationWeeks() >= 6 && weekNumber % 5 == 0;
            weeks.add(buildWeek(weekNumber, request.daysPerWeek(), deload));
        }

        GeneratedProgram program = new GeneratedProgram(
                "Stub Program (%d weeks, %dx/week)".formatted(request.durationWeeks(), request.daysPerWeek()),
                "Deterministic placeholder program generated without calling Claude.",
                parseGoal(request.goal()),
                request.durationWeeks(),
                request.daysPerWeek(),
                weeks,
                "Generated by StubWorkoutPlanAiClient — no real AI call was made."
        );
        return new AiGenerationResult(program, 0, 0);
    }

    private GeneratedWeek buildWeek(int weekNumber, int daysPerWeek, boolean deload) {
        List<GeneratedDay> days = new ArrayList<>();
        for (int dayNumber = 1; dayNumber <= daysPerWeek; dayNumber++) {
            days.add(buildDay(dayNumber, deload));
        }
        return new GeneratedWeek(weekNumber, deload ? "Deload" : "Base", deload, null, days);
    }

    private GeneratedDay buildDay(int dayNumber, boolean deload) {
        List<GeneratedExercise> exercises = new ArrayList<>();
        int sets = deload ? 2 : 3;
        for (int i = 0; i < EXERCISES_PER_DAY; i++) {
            exercises.add(new GeneratedExercise(
                    "Stub Exercise " + (i + 1), i, sets, 6, 10, 120,
                    "Add 2.5kg once you hit the top of the rep range on all sets"));
        }
        return new GeneratedDay(dayNumber, "Day " + dayNumber, null, exercises);
    }

    @Override
    public AiGenerationResult regenerate(GeneratePlanRequest request, TrainingHistorySummary history,
                                          GeneratedProgram previousProgram, String feedback) {
        GeneratedProgram program = generate(request, history).program();
        GeneratedProgram withFeedbackNote = new GeneratedProgram(
                program.name(), program.description(), program.goal(), program.durationWeeks(),
                program.daysPerWeek(), program.weeks(),
                program.coachNotes() + " Feedback noted: " + feedback);
        return new AiGenerationResult(withFeedbackNote, 0, 0);
    }

    private ProgramGoal parseGoal(String goal) {
        if (goal == null) {
            return ProgramGoal.GENERAL;
        }
        try {
            return ProgramGoal.valueOf(goal);
        } catch (IllegalArgumentException e) {
            return ProgramGoal.GENERAL;
        }
    }
}
